/**:
  ros__parameters:
    enable_button: 5
    enable_turbo_button: 4

    axis_linear:
      x: 1
    scale_linear:
      x: 0.2
    scale_linear_turbo:
      x: 0.5

    axis_angular:
      yaw: 2
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0

    deadzone: 0.1

